---
- name: Install pip - Debian
  apt:
    name: "{{ pip_packages|default(omit) }}"
    state: latest
    force: yes
  when: ansible_os_family == "Debian"

- name: Install pip - Archlinux
  pacman:
    state: latest
    name: "{{ pip_packages_arch|default(omit) }}"
  when: ansible_os_family == "Archlinux"

- name: Install pip packages
  pip:
    name: "{{ pip_custom_packages|default(omit) }}"
    state: present
  when: pip_custom_packages is defined
