---
- name: Install pip - Debian
  apt:
    name: "{{ item }}"
    state: latest
    force: yes
  with_items:
    - python-pip
    - python3-pip
  when: ansible_os_family == "Debian"

- name: Install pip - Archlinux
  pacman:
    state: latest
    name: "{{ item }}"
  with_items:
    - python-pip
    - python2-pip
  when: ansible_os_family == "Archlinux"

- name: Install pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ pip_custom_packages | default(omit) }}"
  when: pip_custom_packages is defined
