---
- name: Install pip - Debian
  apt:
    name: "{{ pip_packages_ubuntu|default(omit) }}"
    state: latest
    force: yes
  when:
    - ansible_os_family == "Debian"
    - ansible_lsb.id == "Ubuntu"
    - ansible_lsb.major_release|int < 18

- name: Install pip - Ubuntu 18.04+
  apt:
    name: "{{ pip_packages_ubuntu_18p|default(omit) }}"
    state: latest
    force: yes
  when:
    - ansible_os_family == "Debian"
    - ansible_lsb.id == "Ubuntu"
    - ansible_lsb.major_release|int >= 16

- name: Install pip - Archlinux
  pacman:
    state: latest
    name: "{{ pip_packages_arch|default(omit) }}"
  when: ansible_os_family == "Archlinux"

- name: Install pip packages
  pip:
    name: "{{ pip_custom_packages|default(omit) }}"
    state: present
  when: pip_custom_packages is defined
